"""add datetime

Revision ID: 0baf4cfc855d
Revises: cce0c36f6374
Create Date: 2026-03-21 19:36:46.507181

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0baf4cfc855d"
down_revision = "cce0c36f6374"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.add_column(sa.Column("send_time", sa.DateTime(), nullable=False))
        batch_op.drop_column("time")

    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.add_column(sa.Column("send_time", sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.drop_column("send_time")

    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "time", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_column("send_time")
    # ### end Alembic commands ###
