"""add cascade on userInProject

Revision ID: 3494e8480048
Revises: 48e87bde2476
Create Date: 2026-05-22 03:48:09.057624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3494e8480048'
down_revision = '48e87bde2476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_in_project', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_in_project_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_in_project_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_in_project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_in_project_project_id_fkey'), 'project', ['project_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('user_in_project_user_id_fkey'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
