"""add cascade on notifications

Revision ID: 48e87bde2476
Revises: 20260522_cascade
Create Date: 2026-05-22 03:46:40.685580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e87bde2476'
down_revision = '20260522_cascade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notification_receiver_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('notification_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['receiver_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notification_project_id_fkey'), 'project', ['project_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('notification_receiver_id_fkey'), 'user', ['receiver_id'], ['id'])

    # ### end Alembic commands ###
