"""add unique constraints

Revision ID: b343c2ea0dc5
Revises: 854a44908f79
Create Date: 2026-05-04 23:26:29.185439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b343c2ea0dc5'
down_revision = '854a44908f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_project_receiver', ['project_id', 'receiver_id'])

    with op.batch_alter_table('user_in_project', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_project_user', ['project_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_in_project', schema=None) as batch_op:
        batch_op.drop_constraint('uq_project_user', type_='unique')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('uq_project_receiver', type_='unique')

    # ### end Alembic commands ###
