"""add chat identificator

Revision ID: bb11a7bd8f8c
Revises: 3494e8480048
Create Date: 2026-05-22 14:17:53.995846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb11a7bd8f8c'
down_revision = '3494e8480048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identificator', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('identificator')

    # ### end Alembic commands ###
