"""add cascade deletion messages in chat

Revision ID: c57fd5bea1d5
Revises: e37cc08a86ca
Create Date: 2026-05-20 22:28:01.440515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c57fd5bea1d5'
down_revision = 'e37cc08a86ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('message_chat_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat', ['chat_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('message_chat_id_fkey'), 'chat', ['chat_id'], ['id'])

    # ### end Alembic commands ###
