"""improve user validation

Revision ID: d532c0923851
Revises: 0baf4cfc855d
Create Date: 2026-03-21 20:29:13.542763

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d532c0923851"
down_revision = "0baf4cfc855d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("email", existing_type=sa.TEXT(), nullable=False)
        batch_op.create_unique_constraint(None, ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column("email", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
