"""add cascade delete for files

Revision ID: e0e55db1dd7a
Revises: b343c2ea0dc5
Create Date: 2026-05-13 19:11:10.016053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e55db1dd7a'
down_revision = 'b343c2ea0dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('file_parent_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'file', ['parent_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('file_parent_id_fkey'), 'file', ['parent_id'], ['id'])

    # ### end Alembic commands ###
