"""add command to language model

Revision ID: e37cc08a86ca
Revises: e0e55db1dd7a
Create Date: 2026-05-16 23:09:34.047065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37cc08a86ca'
down_revision = 'e0e55db1dd7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('command', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_column('command')

    # ### end Alembic commands ###
