"""add cascade deletion to project for chats

Revision ID: f27a2da96acf
Revises: c57fd5bea1d5
Create Date: 2026-05-21 10:17:33.311409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27a2da96acf'
down_revision = 'c57fd5bea1d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('chat_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chat_project_id_fkey'), 'project', ['project_id'], ['id'])

    # ### end Alembic commands ###
